name: core
description: " New Flutter package for SQLite database operations."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.8.0-171.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
